Desktop version portfolio
wolterbwambale/mobile-portfolio pull request #5
Opened 2023-03-02 15:57 UTC by wolterbwambale

This is my desktop portfolio version, I added the requirement HTML and CSS.

2023-03-02 18:07 UTC, souad988 requested changes
Hi @wolterbwambale , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/222513479-784354aa-128f-43ba-8bd7-5b06673e9c85.gif)


## Highlights
✔Good use of github workflow
✔Good PR title
✔No linter issues

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-🙏 Changing your PR summary to something better describing the changes done in this feature 😊

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 18:07 UTC, souad988 commented on index.html
>      <section class="contact-us">
Good job here as well your form is centered and section looks good on desktop , **but** Kindly check the background image in this section on figma design and make sure to add it and replicate the given template as much as possible

![Uploading figma contact form background image.PNG…]()

2023-03-02 23:03 UTC, wolterbwambale commented
@souad988 I have add mobile background and worked on responsiveness and replacing the background as required.

2023-03-02 23:38 UTC, Gambit142 requested changes
Hi @wolterbwambale 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- Use of media query between _**768px**_ to _**1440px**_ ✔️ 
- _**Hamburger**_ button doesn't show on the desktop version ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 23:38 UTC, Gambit142 commented on styles.css
>  }
- [ ] Great work making some changes to the `background-image` of the Form section. However, I noticed that the `background-image` used is not the correct one and doesn't correlate with that of the Figma template used. Also, the positioning of the `background-image` is not uniform with that of the Figma template chosen. 👍 

### Your Design

![Screenshot1](https://user-images.githubusercontent.com/77106962/222586926-226759d0-b0b3-41d5-b820-b44deae28b26.png)

### Figma Template

![Screenshot2](https://user-images.githubusercontent.com/77106962/222587275-f0ed5122-f669-4c92-9926-97b4ec54efa1.png)

2023-03-02 23:38 UTC, Gambit142 commented on styles.css
>    background-repeat: no-repeats;
- [ ] Great work making some changes to the `background-image` of the _**top**_ section. However, I noticed that the `background-image` used is not the correct one and doesn't correlate with that of the Figma template used. Also, the positioning of the `background-image` is not uniform with that of the Figma template chosen. 👍 

### Your Design

![Screenshot3](https://user-images.githubusercontent.com/77106962/222587823-9b0bc990-f1e6-4b71-b1e9-bde5176ba7e4.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/222588011-473cd765-d061-417d-a381-51b0b94372b0.png)

2023-03-03 00:14 UTC, wolterbwambale commented
@Gambit142  I have changed the background for mobile and contact me form.

2023-03-03 06:21 UTC, Shedrack-Sunday approved these changes
Hi @wolterbwambale 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

__check the comments for details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-03 06:56 UTC, merged